name: Build and Deploy Windows Container App to Azure App Service

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-to-dev:
    runs-on: windows-latest
    
    steps:
      
    # Check out the repo to the app service VMs
    - uses: actions/checkout@v1
               
    # Use docker login to log into ACR
    - name: Docker login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: jefmartiregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    # Build and push the image to Azure Container Registry
    - name: Build and Push container to ACR
      run: |
        docker build -t jefmartiregistry.azurecr.io/dotnetframework:${{ github.sha }} dotnetwindowsapp/
        docker push jefmartiregistry.azurecr.io/dotnetframework:${{ github.sha }}
